[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["cd ContextManager.API && dotnet restore"]

[phases.build]
cmds = ["cd ContextManager.API && dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "cd ContextManager.API/out && ./ContextManager.API --urls=http://0.0.0.0:$PORT || dotnet ContextManager.API.dll --urls=http://0.0.0.0:$PORT"

